aura-nw/aura-explorer-api

- src/components/account/services/account.service.ts
> Fix bug: Tab Redelegations does not display data because the Redelegate function has not been applied

- src/components/block/dtos/block-latest-params.dto.ts
- src/components/block/dtos/block-params.dto.ts
- src/components/transaction/dtos/transaction-params.dto.ts
- max limit when get blocks, transactions
> [Aura][ExplorerApi][Euphoria][ThuNPA] baseline 20220729_1

- src/migrations/1659686341676-add-column-request-amount-to-table-proposals.ts
- src/shared/entities/proposal.entity.ts
https://github.com/aura-nw/aurascan/issues/764
> [Aura][ExplorerApi][Dev][ThuNPA] add request amount to table proposals

- src/migrations/1660018242123-drop-column-owner-and-balance-table-token-contracts.ts
- src/shared/entities/token-contract.entity.ts
https://github.com/aura-nw/aurascan/issues/364
https://github.com/aura-nw/aurascan/issues/363
> [Aura][ExplorerApi][Dev][ThuNPA] cw721 tokens list

- src/components/contract/repositories/token-contract.repository.ts
- src/components/cw20-token/controllers/cw20-token.controller.ts
- src/components/cw20-token/dtos/token-transaction-params.dto.ts
- src/components/cw20-token/services/cw20-token.service.ts
- src/shared/constants/common.ts
https://github.com/aura-nw/aurascan/issues/363
https://github.com/aura-nw/aurascan/issues/366
> [Aura][ExplorerApi][Dev][ThuNPA] cw20/cw721 transactions list

- src/components/cw20-token/controllers/cw20-token.controller.ts
- src/components/cw20-token/cw20-token.module.ts
- src/components/cw20-token/services/cw20-token.service.ts
- src/shared/constants/common.ts
https://github.com/aura-nw/aurascan/issues/738
> [Aura][ExplorerApi][Dev][ThuNPA] cw20/cw721 tokens list by owner

- src/components/cw721-token/repositories/nft.repository.ts
https://github.com/aura-nw/aurascan/issues/366
> [Aura][ExplorerApi][Dev][ThuNPA] cw721 nft detail add symbol

- src/migrations/1660534506643-add-column-num-tokens-to-table-token-contracts.ts
- src/shared/entities/token-contract.entity.ts
https://github.com/aura-nw/aurascan/issues/814
> [Aura][ExplorerApi][Dev][ThuNPA] cw721 token total supply

- src/components/contract/repositories/token-contract.repository.ts
- src/components/cw721-token/repositories/nft.repository.ts
- src/components/cw721-token/services/cw721-token.service.ts
- src/migrations/1660548244730-add-column-is-burn-to-table-nfts.ts
- src/shared/entities/nft.entity.ts
https://github.com/aura-nw/aurascan/issues/795
> [Aura][ExplorerApi][Dev][ThuNPA] remove burn token inventory

- src/components/schedule/services/influxdb-client.ts
- Update timeout connection for influxdb
> [Thanhhao1986][Serenity] Baseline Serenity 20220816

- src/components/cw721-token/services/cw721-token.service.ts
https://github.com/aura-nw/aurascan/issues/832
> [Aura][ExplorerApi][Dev][ThuNPA] sort nfts

- src/components/contract/repositories/token-contract.repository.ts
- src/components/cw20-token/controllers/cw20-token.controller.ts
- src/components/cw20-token/cw20-token.module.ts
- src/components/cw20-token/services/cw20-token.service.ts
- src/components/cw721-token/repositories/nft.repository.ts
- src/components/cw721-token/services/cw721-token.service.ts
- src/shared/configs/configuration.ts
- src/shared/shared.module.ts
- src/shared/utils/redis.util.ts
https://github.com/aura-nw/aurascan/issues/842
> [Aura][ExplorerApi][Dev][ThuNPA] cw20 token price

- src/components/contract/repositories/token-contract.repository.ts
- src/components/cw20-token/services/cw20-token.service.ts
- src/migrations/1661148687675-update-cw20-token-info-table-token-contracts.ts
- src/shared/entities/nft.entity.ts
- src/shared/entities/token-contract.entity.ts
https://github.com/aura-nw/aurascan/issues/848
https://github.com/aura-nw/aurascan/issues/792
> [Aura][ExplorerApi][Dev][ThuNPA] cw20 tokens list/detail token info

- src/migrations/1661304838438-create-table-token-transactions.ts
- src/shared/entities/token-transaction.entity.ts
https://github.com/aura-nw/aurascan/issues/848
https://github.com/aura-nw/aurascan/issues/859
> [Aura][ExplorerApi][Dev][ThuNPA] create table token transactions

- src/components/account/controllers/account.controller.ts
- src/components/transaction/repositories/transaction.repository.ts
- src/migrations/1661483207924-transaction_create_index.ts
- src/shared/entities/transaction.entity.ts
(cherry picked from commit 0ac47e9f8577050fd46de624af0f09db888cd7a5)
> Fix validator load transaction timeout

- src/components/account/dtos/account-delegation.dto.ts
- src/components/account/dtos/account-redelegation.dto.ts
- src/components/account/dtos/account-unbonding.dto.ts
- src/components/account/services/account.service.ts
- src/components/validator/dtos/lite-validator-output.dto.ts
- src/components/validator/dtos/validator-output.dto.ts
https://github.com/aura-nw/aurascan/issues/939
> [Aura][ExplorerApi][Dev][ThuNPA] add identity validators

- src/migrations/1663039495247-updateRequestTableAddRequestAddress.ts
- src/shared/entities/deployment-requests.entity.ts
(cherry picked from commit 88a0ba014b4be4a552378509b5b1b3b5e97cdbef)
> [Aura][ExplorerApi][Serenity][ThuNPA] baseline 20220914

- src/components/contract/repositories/smart-contract.repository.ts
- src/components/contract/repositories/token-contract.repository.ts
- src/migrations/1663317597034-drop-column-is-minted-table-smart-contracts.ts
- src/shared/entities/smart-contract.entity.ts
https://github.com/aura-nw/aurascan/issues/980
https://github.com/aura-nw/aurascan/issues/1003
> [Aura][ExplorerApi][Dev][ThuNPA] update logic sync cw721 tokens

- src/components/proposal/repositories/proposal-vote.repository.ts
(cherry picked from commit 4fd464c47cce72630679059333a3a63bfa503282)
> [Aura][ExplorerApi][Dev][ThuNPA] validator identity

- src/components/contract/repositories/smart-contract.repository.ts
- src/shared/constants/common.ts
https://github.com/aura-nw/aurascan/issues/1009
> [Aura][ExplorerApi][Dev][ThuNPA] search contracts

- src/components/validator/services/validator.service.ts
(cherry picked from commit 2f699d0874a905efe3d7f37d94f42f8a853eb533)
> [Aura][ExplorerApi][Serenity][ThuNPA] baseline 20220922

- src/components/contract/repositories/smart-contract.repository.ts
* Commit code
* Update logic search contract
* Update search data paging
* Update comment for function
* Update Output getContractByCreator api
* Update Output getContractByCreator api
* Fix incorrect status
* Fix incorrect status
* Fix incorrect status
* Fix incorrect status
* Fix incorrect status
* Fix bug register smart contract to main net
* Updated log sort and record api limit
* Update query get smart contract
* Change the DTO of the attribute
* Change the DTO of the attribute
* Update sort code Ids
* Update logic get code ids of contract
> [Thanhhao1986][Serenity] Baseline code 20220927

- src/components/cw721-token/services/cw721-token.service.ts
https://github.com/aura-nw/aurascan/issues/1131
> [Aura][ExplorerApi][Dev][ThuNPA] encode uri nft

- src/components/cw721-token/services/cw721-token.service.ts
(cherry picked from commit 7fd0313b2dde8fd2e56d517a7bb2da0db6a68a65)
> [Aura][ExplorerApi][Serenity][ThuNPA] baseline 20221010

- src/components/validator/repositories/proposal-vote.repository.ts
https://github.com/aura-nw/aurascan/issues/1200
>  [Aura][ExplorerApi][Serenity] baseline 20221021

- src/components/metric/controllers/metric.controller.ts
- src/components/metric/dtos/cw20-metric-params.dto.ts
- src/components/metric/dtos/token-output.dto.ts
- src/components/metric/services/influxdb-client.ts
- src/components/metric/services/metric.service.ts
- src/components/metric/utils/enum.ts
- Create getTokenByCoinIdMetric api in Metric Controller to get data from Influxdb service to graph FE and display data
> [Thanhao1986][Dev] Update dashboard apis

- src/components/contract/services/contract.service.ts
- Change contractAddress parameter to codeId parameter
> [Thanhhao1986][Dev] Update VerifyContractStatus api

- src/components/contract/repositories/smart-contract.repository.ts
(cherry picked from commit 145631c2fb27783de12710cc13af83d1630f9ead)
> [nthduc95][Serenity] Baseline code 20230224

- src/components/cw20-token/services/cw20-token.service.ts
(cherry picked from commit cb9bc88c7d87d156c8244a44d759f026f71c471e)
> [nthduc95][Euphoria] Baseline code 20230302

- src/components/cw20-token/services/cw20-token.service.ts
- src/components/validator/repositories/delegator-reward.repository.ts
- src/components/validator/services/validator.service.ts
> [nthduc95][Dev] Fix NaN at balance get by owner

- src/components/contract-code/services/contract-code.service.ts
Register CodeID Flow: 
+ Allow non-creator to register contract code type.
> [nthduc95][Dev] Remove check owner when register contract code

- src/components/contract-code/services/contract-code.service.ts
Reverts aura-nw/aura-explorer-api#739
> Revert "[nthduc95][Dev] Remove check owner when register contract code"

- src/components/contract-code/services/contract-code.service.ts
Reverts aura-nw/aura-explorer-api#740
> Revert "[nthduc95][Serenity] Remove check owner when register contract code"

- src/migrations/1679987501767-add-image-column-validator-table.ts
- src/shared/entities/validator.entity.ts
- Tạo file migration thêm cột image_url cho bảng validators
- Bổ sung thuộc tính image_url cho validator entity
> [Thanhhao1986][Dev] Sync validator image

- src/components/validator/controllers/validator.controller.ts
- src/components/validator/dtos/lite-validator-output.dto.ts
- src/components/validator/dtos/validator-info-output.dto.ts
- src/components/validator/dtos/validator-output.dto.ts
- src/components/validator/services/validator.service.ts
- Tạo api validator info để lấy thông tin validators theo mảng operator_address truyền vào
> [Thanhhao1986][Dev] Create Validator info api

- package-lock.json
- package.json
- src/main.ts
- src/shared/utils/redis.util.ts
**What:** 
1. Add bull-board to manage job with ui
**How:** 
1. Implement bull-board by following the document [https://github.com/felixmosh/bull-board#-bull-board](https://github.com/felixmosh/bull-board#-bull-board)
2. Config Nginx set Basic Authentication username and password for endpoint `host/admin/queues` by following the document [https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/)
**What to be reviewd**
1. Config ?
2. Convention ?
> feat: add bull-board

- src/main.ts
- src/shared/utils/redis.util.ts
What:
Remove failed bull-board config.
Why:
Can't query redis key with pattern.
> fix: remove failed bull-board config

- src/components/validator/controllers/validator.controller.ts
- src/components/validator/dtos/lite-validator-output.dto.ts
- src/components/validator/dtos/validator-info-output.dto.ts
- src/components/validator/services/validator.service.ts
- src/migrations/1679987501767-add-image-column-validator-table.ts
- src/shared/entities/validator.entity.ts
- Add image_url to validators entity
- Add new api to get validator info by address
> [nthduc95][main] Baseline code 20230405

- src/components/contract/repositories/smart-contract.repository.ts
- src/migrations/1680502133033-add-column-total-transaction.ts
- src/shared/entities/smart-contract.entity.ts
- add new column total_tx to smart_contract table
> [nthduc95][Dev] Create column total_tx

- src/components/validator/dtos/lite-validator-output.dto.ts
- src/migrations/1681266400447-create-column-voting-power-level.ts
- src/shared/entities/validator.entity.ts
Task: Enhance Validator list view
Implement: add new column voting_power_level to validators table
Related document: https://www.notion.so/aura-network/Epics-0cdf1020154c4c4fa3f533ea1bd1458b?p=5c319fe902a843e6a4a954ece2be7690&pm=s
> [nthduc95][Dev] Enhance Validator list view

- src/main.ts
- src/shared/utils/redis.util.ts
What:
Add prefix to bull-board job because has change from api-explorer-sync: https://github.com/aura-nw/aura-explorer-sync/pull/437/files
Auto load bull job from redis.
What to be reviewed: 
Config? 
Convention?
> fix:(bull-board) add prefix

- src/components/contract/repositories/smart-contract.repository.ts
- src/components/soulbound-token/controllers/soulbound-token.controller.ts
- src/components/soulbound-token/dtos/token-by-receiver-address-output.dto.ts
- src/components/soulbound-token/dtos/token-updated-paras.dto.ts
- src/components/soulbound-token/repositories/soulbound-reject-list.repository.ts
- src/components/soulbound-token/repositories/soulbound-token.repository.ts
- src/components/soulbound-token/repositories/soulbound-white-list.repository.ts
- src/components/soulbound-token/services/soulbound-token.service.ts
- src/components/soulbound-token/soulbound-token.module.ts
- src/migrations/1681440466119-create-column-is-notify-abt-token.ts
- src/migrations/1681444813471-create-soulbound-white-list-table.ts
- src/migrations/1681704169880-create-soulbound-reject-list-table.ts
- src/shared/configs/configuration.ts
- src/shared/constants/common.ts
- src/shared/entities/soulbound-reject-list.entity.ts
- src/shared/entities/soulbound-token.entity.ts
- src/shared/entities/soulbound-white-list.entity.ts
- src/shared/utils/redis.util.ts
**Implement new API for abt token:**
+ Get white-list account for create new abt token.
+ Notification for new un-claimed abt token.
+ Reject abt token from another user.
> [nthduc95][Dev] Enhance ABT prevent spam

- .env.example
- src/components/validator/controllers/validator.controller.ts
- src/components/validator/dtos/delegation-output.dto.ts
- src/components/validator/dtos/delegation-params.dto.ts
- src/components/validator/dtos/validator-info-output.dto.ts
- src/components/validator/repositories/delegation.repository.ts
- src/components/validator/repositories/delegator-reward.repository.ts
- src/components/validator/services/validator.service.ts
- src/migrations/1682491012763-add-column-bonded_height-to-validator-table.ts
- src/shared/configs/configuration.ts
- src/shared/constants/common.ts
- src/shared/entities/validator.entity.ts
- src/shared/utils/service.util.ts
What: migrate api validator to horoscopev2
Put bonded_height to sync service
Taiga: https://taiga.aura.network/project/aurascan-2/task/223
> feat:(horoscopev2/validator) migrate api to horoscopev2

- src/components/contract/contract.module.ts
- src/components/contract/services/contract.service.ts
- src/components/soulbound-token/controllers/soulbound-token.controller.ts
- src/components/soulbound-token/services/soulbound-token.service.ts
- src/migrations/1683183214592-add-column-abt-ipfs.ts
- src/shared/constants/common.ts
- src/shared/entities/soulbound-token.entity.ts
- src/shared/utils/contract.util.ts
- Refactor code.
- Reduce ipfs request at abt detail.
> [nthduc95][Dev] Enhance ipfs request

- src/components/validator/services/validator.service.ts
(cherry picked from commit d464920cc30992f59836346234c92da26e438a30)
> add validator_identity

- src/components/user/controllers/users.controller.ts
- src/components/user/dtos/update-user.dto.ts
- src/components/user/user.service.ts
Can only update user name.
https://taiga.aura.network/project/aurascan-2/task/247
> fix: crud user can only update user name

- src/components/name-tag/dtos/store-name-tag-params.dto.ts
- src/components/name-tag/repositories/name-tag.repository.ts
- src/components/name-tag/services/name-tag.service.ts
- src/migrations/1688455355281-add-enterprise-url-to-name-tag.ts
- src/shared/entities/name-tag.entity.ts
#844 add url to nametag
#846 fix not require url in name tag
> chore: add url to nametag (#844)

- src/components/account/services/account.service.ts
- src/components/cw20-token/services/cw20-token.service.ts
Add thêm where theo owner để lấy chỉnh xác owner cần lấy.
> fix: Filter amount cw20 according to owner

- src/auth/password/dtos/login-with-password.dto.ts
- src/auth/password/dtos/login-with-password.response.dto.ts
- src/auth/password/password-auth.controller.ts
- src/auth/password/password-auth.module.ts
- src/auth/password/password-auth.service.ts
- src/shared/constants/common.ts
> feat: add login with password

- src/components/user/controllers/users.controller.ts
- src/components/user/dtos/change-password.dto.ts
- src/components/user/user.service.ts
> feat: add change password

- src/auth/password/dtos/reset-password.dto.ts
- src/auth/password/password-auth.controller.ts
- src/components/mail/mail.service.ts
- src/components/mail/templates/recovery-password.hbs
- src/components/user/user.service.ts
- src/migrations/1689069710311-add-reset-password-token-to-user.ts
- src/shared/constants/common.ts
- src/shared/entities/user.entity.ts
> feat: add reset password

- src/auth/google/google-oauth.service.ts
- src/components/google/dtos/google-oauth-login.response.dto.ts
- src/components/user/user.service.ts
When user login google need to response provider for detect login method.
> fix: add provider to response

- src/components/cw20-token/services/cw20-token.service.ts
get cw20 image from horosocpe v2, if not get from DB
> fix: fix token image token table

- src/components/user/dtos/change-password.dto.ts
- src/components/user/user.service.ts
- src/shared/constants/common.ts
Add create password when the first time google user change password.
> chore: add create password for google user

- src/components/user/dtos/change-password.dto.ts
- src/components/user/user.service.ts
- src/shared/constants/common.ts
* chore: add create password for google user
* chore: change text content
> chore: add create password for google user (#882)

- src/auth/google/google-oauth.service.ts
- src/components/user/user.service.ts
Active user on login with google
> revamp: login user with google

- src/app.service.ts
- src/shared/configs/configuration.ts
- src/shared/configs/module-options.ts
> remove unused code

- src/components/public-name-tag/repositories/public-name-tag.repository.ts
Fix search name tag admin site
PR: 897
> fix: search public name tag (#897)

- src/auth/google/google-oauth.service.ts
- src/components/public-name-tag/controllers/public-name-tag.controller.ts
- src/components/public-name-tag/dtos/store-public-name-tag-params.dto.ts
- src/components/public-name-tag/dtos/update-public-name-tag-params.dto.ts
- src/components/public-name-tag/services/public-name-tag.service.ts
- src/components/user/user.service.ts
- Set maxlength 35 for nametag
- Check role user login to admin
- Remove address from update name tag payload
> fix: Enhance admin nametag

- src/auth/jwt/jwt-auth.service.ts
- src/auth/jwt/jwt-auth.strategy.ts
- src/components/user/user.service.ts
- src/migrations/1691651376369-add-last-required-login-to-user.ts
- src/shared/constants/common.ts
- src/shared/entities/user.entity.ts
- src/shared/utils/service.util.ts
require login when change pwd successfully
> fix: require login when change pwd successfully

- src/auth/password/dtos/create-user-with-password.dto.ts
- src/auth/password/dtos/login-with-password.dto.ts
- src/auth/password/dtos/reset-password.dto.ts
- src/shared/constants/common.ts
Change content of message.
Transform email to lowercase.
> fix: msg require login when change pwd successfully

- .env.example
- src/components/private-name-tag/repositories/private-name-tag.repository.ts
- Add field `note` to response user/private-name-tag
- Add config KMS to file `.env`
> add field note to response

- src/components/metric/services/metric.service.ts
Fix bug duplicate when drag the chart
> fix: update time range

- src/components/metric/controllers/metric.controller.ts
- src/components/metric/dtos/cw20-metric-params.dto.ts
- src/components/metric/services/metric.service.ts
Add step to query param for flexible data point
> fix: Fix data point chart

- src/components/soulbound-token/controllers/soulbound-token.controller.ts
- src/components/soulbound-token/services/soulbound-token.service.ts
Add new endpoint to count ABT by receiver
> Fix: add new endpoint to count sbt by receiver

- src/components/cw20-token/services/cw20-token.service.ts
- src/migrations/1694571809657-add-denom-column-token-market.ts
- src/shared/entities/token-markets.entity.ts
- Add column denom, decimal to table token_market.
- Get ibc from DB with denom
> Feat: implement ibc token

- src/components/cw20-token/services/cw20-token.service.ts
- src/migrations/1694571809657-add-denom-column-token-market.ts
- src/shared/entities/token-markets.entity.ts
> implement ibc token (#924)

- src/components/queues/cw4973/cw4973.module.ts
- src/components/queues/cw4973/cw4973.processor.ts
- src/components/queues/queues.module.ts
- src/components/sync-point/repositories/sync-point.repository.ts
- src/main.ts
- src/migrations/1692954853079-create-sync-point.ts
- src/shared/configs/configuration.ts
- src/shared/constants/common.ts
- src/shared/entities/sync-point.entity.ts
- src/shared/utils/service.util.ts
merge cw4973 to api:
create queue
[move logic from sync service ](https://github.com/aura-nw/aura-explorer-sync/blob/74a81f0ad359ac4e8195ce4cf642e4689e787cda/src/processor/smart-contracts.processor.ts#L43)
> merge cw4973 to api

- src/components/private-name-tag/services/private-name-tag.service.ts
Fix error update with nameTag is null
> fix 500, update with nameTag is null

- src/components/private-name-tag/repositories/private-name-tag.repository.ts
Fix search private name tag with address
> fix search address

- src/components/private-name-tag/controllers/private-name-tag.controller.ts
- src/components/private-name-tag/repositories/private-name-tag.repository.ts
- src/components/private-name-tag/services/private-name-tag.service.ts
- Fix Error code 500 when name tag null/undefined
- Add return total favorite
> fix bug when name tag null/undefined

- src/components/export-csv/services/export-csv.service.ts
- src/shared/constants/common.ts
Fix bug limit 1000 record export data.
Do horoscope chỉ trả về tối đa 100 record 1 lần, nên cần loop để query trả về 1000 record.
> [Dev][Export_CSV] fix bug limit 1000 record csv

- src/components/export-csv/services/export-csv.service.ts
- src/shared/constants/common.ts
#959 fix bug limit 1000 records csv
> [Serenity][Export_CSV] baseline/serenity_20231016

- src/components/export-csv/controllers/export-csv.controller.ts
> chore: debug original user -ip

- src/shared/helpers/transaction.helper.ts
> [Serenity][Export_CSV] serenity_20231017

- src/components/export-csv/controllers/export-csv.controller.ts
Reverts aura-nw/aura-explorer-api#962
> Revert "chore: debug original user -ip"

- src/main.ts
- src/shared/guards/custom-csv-throttler-guard.ts
Get original ip for throttler because of we use proxy
> fix: get original ip for throttler

- src/main.ts
- src/shared/guards/custom-csv-throttler-guard.ts
> [Export_CSV] Baseline/serenity_20231018_get_original_ip_for_throttler

- src/shared/helpers/transaction.helper.ts
- Fix lỗi 2 giá trị amount đang bị gom chung 1 dòng.
> [Dev][Export_CSV] fix bug export csv

- src/shared/helpers/transaction.helper.ts
> [Serenity][Export_CSV] baseline serenity_20231019

- src/components/contract/services/contract.service.ts
- src/components/soulbound-token/services/soulbound-token.service.ts
- src/shared/constants/common.ts
Fix get CW4973 image url form horoscope at account detail page.
> [DEV][Fix_CW4973] fix get media info from horoscope

- src/components/export-csv/services/export-csv.service.ts
> [Serenity][Export_CSV] Fixing/fix export config csv

- src/shared/helpers/transaction.helper.ts
(cherry picked from commit 8194f4677b45baecc78ca86c5ddf70b7abef21d9)
> [Serenity][Export_CSV] Baseline/serenity 20231025

- src/shared/helpers/transaction.helper.ts
> [Euphoria][Export_CSV] Baseline/euphoria 20231025

- src/components/export-csv/services/export-csv.service.ts
> [Euphoria][Export_CSV] Fixing/fix export config csv 

- src/components/private-name-tag/services/private-name-tag.service.ts
- src/components/public-name-tag/services/public-name-tag.service.ts
Add thêm xử lí check type của address.
> [DEV][NAME_TAG] Fixing/fix validate name tag

- src/components/queues/notification/notification.processor.ts
- src/components/queues/notification/utils/notification.util.ts
Fix bug notiifcation at token transfer
> [DEV][WATCH_LIST] Fixing/fix notification token transfer

- src/components/watch-list/dto/create-watch-list.dto.ts
- src/components/watch-list/validators/match-type.ts
> [DEV][CRUD][WATCH-LIST] fix validate watch list

- src/components/notification/controllers/notification.controller.ts
- src/components/notification/dtos/get-notification-param.dto.ts
- src/components/notification/services/notification.service.ts
- src/components/queues/notification/notification.processor.ts
- src/components/queues/notification/repositories/notification.repository.ts
- src/components/queues/notification/utils/notification.util.ts
- src/components/user/user.service.ts
- src/shared/constants/common.ts
- add limit offset for notification list.
- fix bug/logic notification (add filter limit 100 notification per day)
- fix register notification token
> [DEV][WATCH_LIST] Fixing/fix watch list notification

- package-lock.json
- package.json
- src/components/encryption/encryption.service.ts
https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html
> [DEV][MIGRATE-AWS-CODE]

- src/components/notification/dtos/get-notification-param.dto.ts
- src/components/queues/notification/utils/notification.util.ts
- src/components/user/controllers/users.controller.ts
- src/components/user/user.service.ts
- Fix NFT notification return image and animation.
- Add endpoint to delete notification when user log out.
> [DEV][WATCH_LIST] Fixing/fix nft notification

- package-lock.json
- package.json
- src/components/encryption/encryption.service.ts
> [SERENITY][MIGRATE-AWS-CODE]

- package-lock.json
- package.json
- src/components/encryption/encryption.service.ts
> [EUPHORIA][MIGRATE-AWS-CODE]

- src/components/queues/notification/notification.processor.ts
- src/components/queues/notification/utils/notification.util.ts
- src/components/user/controllers/users.controller.ts
- src/components/user/user.service.ts
- src/migrations/1699522851065-deleteColumnNotification.ts
- src/shared/configs/configuration.ts
- src/shared/constants/common.ts
- src/shared/entities/notification.entity.ts
- Fix push notification to multipe device.
- Fix duplicate notification at execute transaction.
> [DEV][WATCH_LIST] Fixing/fix multiple notification

- src/auth/jwt/jwt-auth.service.ts
- src/auth/jwt/jwt-auth.strategy.ts
- src/auth/password/dtos/create-user-with-password.dto.ts
- src/auth/password/dtos/login-with-password.dto.ts
- src/auth/password/dtos/reset-password.dto.ts
- src/components/user/user.service.ts
- src/migrations/1691651376369-add-last-required-login-to-user.ts
> [SERENITY][AUTHENTICATION] require login when change password

- src/components/user/controllers/users.controller.ts
- src/components/user/user.service.ts
> [SERENITY][WATCH_LIST] Fixing/fix delete notification token

- src/components/queues/notification/notification.processor.ts
- src/components/queues/notification/utils/notification.util.ts
- src/shared/configs/configuration.ts
- src/shared/constants/common.ts
> [SERENITY][WATCH_LIST] Baseline/serenity 20231113

- src/shared/constants/common.ts
Fix bug: Chỉ hiển thị các transaction success, không hiển thị các transaction fail
> [DEV][WATCH_LIST] Fix display fail TX at notification.

- src/shared/constants/common.ts
> [SERENITY][WATCH_LIST] Baseline/serenity_20231120

- src/shared/constants/common.ts
> [EUPHORIA][WATCH_LIST] Baseline/euphoria_20231120

- package-lock.json
- package.json
Reverts aura-nw/aura-explorer-api#1009
> Revert "[DEV][DEPENDENCIES] Fixing/dependencies/class validator 0.14.0"

- src/components/chain-info/chain-info.controller.ts
- src/components/chain-info/chain-info.module.ts
- src/components/chain-info/chain-info.service.ts
- src/components/chain-info/dto/chain-info-response.dto.ts
- src/components/chain-info/dto/create-chain-info.dto.ts
- src/components/chain-info/dto/update-chain-info.dto.ts
- src/components/chain-info/validator/is-unique.validator.ts
- src/components/components.module.ts
- src/components/cw20-token/controllers/cw20-token.controller.ts
- src/components/cw20-token/cw20-token.module.ts
- src/components/cw20-token/dtos/create-cw20-token.dto.ts
- src/components/cw20-token/dtos/create-ibc.dto.ts
- src/components/cw20-token/dtos/cw20-token-market-params.dto.ts
- src/components/cw20-token/dtos/cw20-token-response.dto.ts
- src/components/cw20-token/dtos/ibc-response.dto.ts
- src/components/cw20-token/dtos/update-cw20-token.dto.ts
- src/components/cw20-token/dtos/update-ibc.dto.ts
- src/components/cw20-token/services/cw20-token.service.ts
- src/components/cw20-token/validators/is-unique-many-column.validator.ts
- src/components/cw20-token/validators/is-unique.validator.ts
- src/migrations/1701052101011-add-chain-id-to-token-market.ts
- src/migrations/1701144278720-remove-code-id-from-token-market.ts
- src/migrations/1701145590378-add-unique-chain-id-denom-to-token-markets.ts
- src/migrations/1701245216668-create-chain-info.ts
- src/shared/entities/chain-info.entity.ts
- src/shared/entities/token-markets.entity.ts
> [Serenity][Manage Connected Chain]

- src/components/export-csv/services/export-csv.service.ts
- src/shared/constants/transaction.ts
> [SERENITY][COIN_TRANSFER] Baseline/serenity 20231205

- src/components/export-csv/services/export-csv.service.ts
- src/shared/helpers/transaction.helper.ts
> [SERENITY][COINS_TRANSFER] Baseline/serenity 20231205

- src/components/export-csv/services/export-csv.service.ts
- src/components/queues/notification/notification.processor.ts
- src/components/queues/notification/utils/notification.util.ts
- src/shared/constants/common.ts
- src/shared/constants/transaction.ts
- src/shared/helpers/transaction.helper.ts
> [MAIN][COIN_TRANSFER] Baseline/main20231206

- src/components/export-csv/export-csv.module.ts
- src/components/export-csv/services/export-csv.service.ts
- src/components/queues/notification/notification.module.ts
- src/components/queues/notification/utils/notification.util.ts
- src/shared/helpers/transaction.helper.ts
> [IBC][Serenity] Baseline/serenity 20231221

- src/components/queues/notification/utils/notification.util.ts
- src/shared/helpers/transaction.helper.ts
> [IBC][SERENITY] Baseline/serenity 20231222

- src/components/export-csv/export-csv.module.ts
- src/components/export-csv/services/export-csv.service.ts
- src/components/queues/notification/notification.module.ts
- src/components/queues/notification/utils/notification.util.ts
- src/shared/helpers/transaction.helper.ts
> [IBC][EUPHORIA] Baseline/euphoria 20231225

- src/components/cw20-token/dtos/create-cw20-token.dto.ts
- src/components/cw20-token/dtos/create-ibc.dto.ts
- src/migrations/1703232894156-add-official-site-social-profiles-in-to-token-market.ts
- src/shared/entities/token-markets.entity.ts
> [Serenity][IBC Phase 2] Baseline/serenity 20231228

- src/components/cw20-token/repositories/token-markets.repository.ts
> [Serenity] Fix ibc holder statistic

- src/components/account/controllers/account.controller.ts
- src/components/account/services/account.service.ts
- src/components/cw20-token/repositories/token-markets.repository.ts
- src/components/cw20-token/services/cw20-token.service.ts
- src/components/queues/token/token.module.ts
- src/components/queues/token/token.processor.ts
- src/migrations/1703573585592-remove-sync-status-table.ts
- src/migrations/1704701919692-add-token-holder-statistic.ts
- src/shared/constants/common.ts
- src/shared/entities/token-holder-statistic.entity.ts
- src/shared/entities/token-markets.entity.ts
> [SEI] Baseline/sei 20241601

- src/components/cw20-token/dtos/create-cw20-token.dto.ts
- src/components/cw20-token/dtos/create-ibc.dto.ts
- src/migrations/1703232894156-add-official-site-social-profiles-in-to-token-market.ts
> [EUPHORIA][COIN_TOKEN] baseline euphoria 20240118

- src/components/account/controllers/account.controller.ts
- src/components/account/services/account.service.ts
- src/components/components.module.ts
- src/components/cw20-token/controllers/cw20-token.controller.ts
- src/components/cw20-token/dtos/create-cw20-token.dto.ts
- src/components/cw20-token/dtos/create-ibc.dto.ts
- src/components/cw20-token/repositories/token-markets.repository.ts
- src/components/cw20-token/services/cw20-token.service.ts
- src/components/queues/cw4973/cw4973.module.ts
- src/components/queues/cw4973/cw4973.processor.ts
- src/components/queues/notification/notification.module.ts
- src/components/queues/token/token.module.ts
- src/components/queues/token/token.processor.ts
- src/migrations/1703232894156-add-official-site-social-profiles-in-to-token-market.ts
- src/migrations/1703573585592-remove-sync-status-table.ts
- src/migrations/1704701919692-add-token-holder-statistic.ts
- src/shared/constants/common.ts
- src/shared/entities/sync-status.entity.ts
- src/shared/entities/token-holder-statistic.entity.ts
- src/shared/entities/token-markets.entity.ts
- src/shared/index.ts
> [MAIN][COIN_TOKEN] Baseline/main 20240123

- src/components/queues/token/token.processor.ts
> [SERENITY][SYNC_PRICE] Baseline/serenity 20240124

- src/components/queues/token/token.module.ts
- src/components/queues/token/token.processor.ts
- src/migrations/1706152426601-create-column-explorer-id-token-markets.ts
- src/shared/configs/configuration.ts
- src/shared/constants/common.ts
- src/shared/entities/explorer.entity.ts
- src/shared/entities/token-markets.entity.ts
- Add column explorer_id to table token_markets
- Implement sync token holder statistic for multi-chain SEI and AURA.
> [Dev][Multi-chain] Token Markets and sync holder statistics

- src/components/account/account.module.ts
- src/components/account/controllers/account.controller.ts
- src/components/account/services/account.service.ts
- src/components/cw20-token/cw20-token.module.ts
- src/components/cw20-token/repositories/token-markets.repository.ts
- src/components/cw20-token/services/cw20-token.service.ts
- src/components/queues/token/token.processor.ts
- src/migrations/1706502043813-add-chain-info-to-explorer.ts
- src/shared/configs/configuration.ts
- src/shared/constants/common.ts
- src/shared/entities/explorer.entity.ts
- src/shared/shared.module.ts
- src/shared/utils/rpc.util.ts
- src/shared/utils/service.util.ts
- Add two new column minimal_denom, decimal to Explorer table.
- Implement get cw20 statistics multi-chain
- Implement get cw20 total holder multi-chain
> [DEV][Multi-chain] Implement get CW20 Holder

- package-lock.json
- package.json
- src/components/queues/token/token.module.ts
- src/components/queues/token/token.processor.ts
- src/migrations/1708337885523-remove-explorer-from-asset.ts
- src/shared/constants/common.ts
- src/shared/entities/asset.entity.ts
- src/shared/entities/explorer.entity.ts
- src/shared/utils/service.util.ts
Update typeorm to 0.2.40 to support upsert
Remove explorer from asset
Sync data from horoscope
> [Dev][Asset Table]: sync data

- src/components/asset/repositories/assets.repository.ts
- src/components/cw20-token/repositories/token-markets.repository.ts
- src/components/queues/token/token.processor.ts
- src/migrations/1708939691028-add-date-to-token-holder-statisitic.ts
- src/shared/constants/common.ts
- src/shared/entities/token-holder-statistic.entity.ts
Sync holder for asset
Clean asset holder older than 2 day
> [Dev][Asset Table]: Sync holder

- src/components/asset/repositories/assets.repository.ts
- src/components/asset/services/asset.service.ts
- Fix search:  search denom/address fix thành search chính xác.
- Fix get asset detail.
> [DEV][Asset Table] fix ibc get detail

- package-lock.json
- package.json
- src/app.module.ts
- src/components/asset/asset.module.ts
- src/components/asset/controllers/asset.controller.ts
- src/components/asset/dtos/asset-params.dto.ts
- src/components/asset/dtos/cw20-token-market-params.dto.ts
- src/components/asset/dtos/get-asset.dto.ts
- src/components/asset/repositories/assets.repository.ts
- src/components/asset/services/asset.service.ts
- src/components/cw20-token/cw20-token.module.ts
- src/components/cw20-token/repositories/token-markets.repository.ts
- src/components/export-csv/export-csv.module.ts
- src/components/export-csv/services/export-csv.service.ts
- src/components/queues/notification/notification.module.ts
- src/components/queues/notification/utils/notification.util.ts
- src/components/queues/token/token.module.ts
- src/components/queues/token/token.processor.ts
- src/migrations/1707986149669-create-asset.ts
- src/migrations/1708313977334-migration-data-to-assets.ts
- src/migrations/1708337885523-remove-explorer-from-asset.ts
- src/migrations/1708939691028-add-date-to-token-holder-statisitic.ts
- src/migrations/1709173688516-add-coin-info-to-asset.ts
- src/shared/constants/common.ts
- src/shared/entities/asset.entity.ts
- src/shared/entities/explorer.entity.ts
- src/shared/entities/token-holder-statistic.entity.ts
- src/shared/index.ts
- src/shared/utils/service.util.ts
* #1100 
* #1103 
* #1105 
* #1109
* #1110
* #1111 
* #1112
* #1113 
* #1114 
* #1115
* #1116
> [SERENITY][Asset Table] Baseline/serenity 20240301

- src/shared/constants/transaction.ts
> [DEV][Multi-chain] Fixing/fix transaction type export

- src/components/export-csv/dtos/export-csv-param.dto.ts
- src/components/export-csv/services/export-csv.service.ts
- src/shared/constants/common.ts
> [DEV][Multi-Chain] add evm address to export csv

- src/auth/password/password-auth.controller.ts
- src/components/mail/mail.service.ts
- src/components/queues/send-mail/send-mail.processor.ts
- src/components/user/user.service.ts
- src/migrations/1712030125133-add-url-column.ts
- src/shared/entities/explorer.entity.ts
Implement send mail reset password at evmos. 
=> Redirect evmos side.
> [DEV][Multi-Chain] Fix multi chain send mail

- src/components/export-csv/services/export-csv.service.ts
- src/shared/constants/common.ts
- src/shared/helpers/transaction.helper.ts
Execute Tx: add column evm_tx_hash to csv.
> [DEV][Multi-Chain] Feat/multi chain/add column evm tx hash csv

- src/components/account/services/account.service.ts
- src/components/asset/repositories/assets.repository.ts
- src/components/export-csv/services/export-csv.service.ts
- src/components/queues/token/token.processor.ts
- src/shared/constants/common.ts
- src/shared/helpers/transaction.helper.ts
sync symbol and name of Erc20 from horoscope.
> [DEV][Multi-Chain-v2] Sync symbol and name for asset erc20

- package.json
- src/components/asset/repositories/assets.repository.ts
- src/migrations/1712030125133-migration-evm-address.ts
> [SERENITY][Multi-Chain-v2] Implement migrate data evm address

- src/components/export-csv/services/export-csv.service.ts
- src/migrations/1712806916760-add-evm-column.ts
- src/shared/constants/common.ts
- src/shared/entities/explorer.entity.ts
- src/shared/helpers/transaction.helper.ts
(cherry picked from commit 92be15d15ec6606f8268c1a048372aa04eedfee5)
> [SERENITY][Multi-Chain-v2] Baseline/serenity 20240412

- src/components/private-name-tag/services/private-name-tag.service.ts
- src/components/public-name-tag/services/public-name-tag.service.ts
- src/components/watch-list/watch-list.service.ts
- src/shared/constants/common.ts
Thêm xử lí check null address khi Create name tag
> [DEV][Multi-Chain-V2] Fixing/fix null address name tag

- src/components/export-csv/services/export-csv.service.ts
- src/components/private-name-tag/services/private-name-tag.service.ts
- src/components/public-name-tag/services/public-name-tag.service.ts
- src/components/queues/token/token.processor.ts
- src/components/watch-list/watch-list.service.ts
- src/shared/constants/common.ts
- src/shared/constants/transaction.ts
- src/shared/helpers/transaction.helper.ts
> [SERENITY][Multi-Chain-V2] Baseline/serenity 20240419

- src/components/queues/token/token.processor.ts
> [SERENITY][Multi-Chain-V2] Baseline/serenity_20240424

- src/components/asset/asset.module.ts
- src/components/asset/controllers/asset.controller.ts
- src/components/asset/dtos/update-asset-dto.ts
- src/components/asset/repositories/assets.repository.ts
- src/components/asset/services/asset.service.ts
- src/migrations/1717123103158-add-overview-info-asset.ts
- src/shared/entities/asset.entity.ts
Admin site: Impl update token info
> admin: impl update token info

- src/components/export-csv/services/export-csv.service.ts
- src/components/private-name-tag/controllers/private-name-tag.controller.ts
- src/shared/constants/common.ts
- src/shared/constants/transaction.ts
- src/shared/helpers/transaction.helper.ts
Add export csv ERC721.
Docs: https://taiga.aura.network/project/aurascan-2/task/608
> [DEV] Add export erc721 transfer

- src/components/export-csv/services/export-csv.service.ts
- src/components/private-name-tag/controllers/private-name-tag.controller.ts
- src/shared/constants/common.ts
- src/shared/constants/transaction.ts
- src/shared/helpers/transaction.helper.ts
> [SERENITY] Baseline/serenity 20240614

- src/components/asset/repositories/assets.repository.ts
- src/components/queues/token/token.processor.ts
> [DEV] Fix sync asset

- src/components/asset/repositories/assets.repository.ts
- src/components/queues/token/token.processor.ts
- src/shared/utils/service.util.ts
- Change raw sql to ORM
- Add try catch job
- Add log get data api
> [SERENITY] Fix/sync asset

- src/shared/constants/common.ts
> [SERENITY] add denom missing (#1184)

- src/components/export-csv/controllers/export-csv.controller.ts
- src/components/export-csv/services/export-csv.service.ts
- src/shared/helpers/transaction.helper.ts
- Change field `Message` --> `Method`
- Fix wrong name function
> [DEV] Fix/wrong field export csv erc721

- src/components/export-csv/controllers/export-csv.controller.ts
- src/components/export-csv/services/export-csv.service.ts
- src/shared/helpers/transaction.helper.ts
> [SERENITY] add convert camelCase --> PascalCase method (#1186)

- src/micro3-campaign/micro3-campaign.service.ts
> [SERENITY] Micro3: change env --> staging (#1188)

- src/micro3-campaign/const/common.ts
- src/micro3-campaign/micro3-campaign.service.ts
- src/shared/configs/configuration.ts
Impl verify Punkga Quest
PRs:
- #1191
> [SERENITY] impl verify punkga quest

- src/micro3-campaign/const/common.ts
- src/micro3-campaign/micro3-campaign.service.ts
- src/shared/configs/configuration.ts
> [MAIN] impl verify punkga quest (#1192)

- src/components/queues/token/token.processor.ts
> [SERENITY] hardcode type erc20

- src/components/asset/services/asset.service.ts
> [SERENITY] Remove query asset condition coin is not null (#1197)

- src/components/asset/repositories/assets.repository.ts
- Remove check name is null
- Remove check case sensitive denom
Bug 3 in: https://taiga.aura.network/project/aurascan-2/task/671
> [DEV] Remove check name is null and case sensitive

- src/components/asset/repositories/assets.repository.ts
> [SERENITY] Remove check name is null and case sensitive

- src/components/queues/token/token.processor.ts
Fix too large request to horoscope with many assets
PRs:
- #1201 
- #1202
> [SERENITY] Baseline/serenity 20240801
